version: '3.8'

services:
  api:
    build: . 
    container_name: algebra_analyser_api
    ports:
      - "8000:8000" 
    volumes:
      - ./src:/app/src 
    command: uvicorn src.core_studies.interface.api.main:app --host 0.0.0.0 --port 8000 --reload